# Disable out-of-border teleportation
disable-out-of-border-teleport: true

# -------- Borders --------

worlds:
  world_newhorizon:
    border_size: 1000
    center_x: 0
    center_z: 0
  world_resource:
    border_size: 2000
    center_x: 100
    center_z: -200
  world_resource_nether:
    border_size: 2000
    center_x: 100
    center_z: -200
  world_resource_the_end:
    border_size: 2000
    center_x: 100
    center_z: -200